project:
  type: website
  output-dir: docs

website:
  title: "Visietool Toetsen"
  navbar:
    background: '#9E8E67'
    left:
      - href: index.qmd
        text: Home
      - href: werkwijze.qmd
        text: Werkwijze

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    link-external-newwindow: false