project:
  type: website
  output-dir: docs

website:
  title: "Visietool Toetsen 2.0"
  search: false
  navbar:
    background: '#F4D9DC'
    left:
      - href: index.qmd
        text: Home
      - href: werkwijze.qmd
        text: Werkwijze
    right:
      - href: https://www.npuls.nl/
        text: "<img src='images/npuls-logo.png' alt='NPULS' height='30'/>"
        aria-label: NPULS
      # - href: https://github.com/Werkgroep-Toetsen-Op-Afstand/visietool-toetsen
      #   icon: github
      #   aria-label: GitHub


format:
  html:
    theme: npuls.scss
    # css: styles.css
    toc: false
    link-external-newwindow: false
    