project:
  type: website
  output-dir: docs

website:
  title: "Visietool Toetsen 2.0"
  search: true
  navbar:
    logo: images/npuls-logo.png
    background: '#D6E2FD'
    # left:
    #   - href: index.qmd
    #     text: Home
    #   - href: workshop.qmd
    #     text: Workshop
    #   - href: voorbereiding.qmd
    #     text: Voorbereiding
    #   - href: tijdens-workshop.qmd
    #     text: Tijdens Workshop
    #   - href: vervolg.qmd
    #     text: Vervolg
    #   - href: contact.qmd
    #     text: Contact

    # right:
    #   - text: "NL"
    #   - menu:
    #       - text: "EN"

    #   - href: https://www.npuls.nl/
    #     text: "<img src='images/npuls-logo.png' alt='NPULS' height='30'/>"
    #     aria-label: NPULS
      # - href: https://github.com/Werkgroep-Toetsen-Op-Afstand/visietool-toetsen
      #   icon: github
      #   aria-label: GitHub


format:
  html:
    theme: npuls.scss
    # css: styles.css
    toc: false
    link-external-newwindow: false
    