## Tijdens de sessie 

Begeleid de deelnemers stap voor stap door onderstaande procedure.  

### Stap 1

Geef aan de start van de sessie een korte toelichting op het doel en de werkwijze van de Visietool. Je kunt hier de [PowerPoint] (200924Introductievideo.pptx) of de [Instructievideo] (https://youtu.be/irJLWzgdX7g) voor gebruiken. Licht hier toe dat jij de moderator bent en wie notuleert. 

### Stap 2

Start de Mentimeter op, klik op ‘Present’, en laat de betrokkenen met hun laptop of telefoon deelnemen aan de Mentimeter door de code die bovenin de dia’s van de presentatie staat in te vullen in [www.menti.com](www.menti.com).  

:::{.repeat}

### Stap 3

Vraag deelnemers de eerste dimensie en de bijbehorende twee componenten met stellingen te lezen op het scherm, of vanaf de uitgeprinte hand-out. Laat de deelnemers per component een keuze maken in de mentimeter voor één van de stellingen (keuze voor 1, 2 of 3): welke stelling past volgens hen het beste bij hoe zij de opleiding (in de toekomst) voor zich zien? Licht toe dat de schuingedrukte zinnen bij de stellingen mogelijke verantwoordingen zijn, en deze niet van toepassing hoeven te zijn. De deelnemers kunnen voor zichzelf hun keuze en hun motivatie daarvoor op de hand-out invullen. Vervolgens vullen de betrokkenen in de Mentimeter in welke stellingen (1, 2 of 3) zij hebben gekozen bij de twee componenten van deze dimensie. Geef voor deze stap maximaal 5 minuten de tijd. 

### Stap 4

Laat de groep nu de resultaten in de Mentimeter zien. Laat deelnemers hun keuzes onderbouwen en laat hen met elkaar in gesprek gaan over de overeenkomsten en verschillen in opvattingen, met als doel om tot een gezamenlijk besluit te komen. Neem hier ongeveer 10 minuten de tijd voor. Laat de notulist goed notuleren; het gaat niet om de uiteindelijke score, maar de onderbouwing ervan.  

**Let op**: in de grafiek zie je niet altijd hoe vaak gescoord is op een item. Wanneer je de muis over de grafiek beweegt, kun je dit wel zien. 

**Herhaal stap 3 en 4 voor elke dimensie.**

Inhoudelijke toelichting:  
Bij dimensie 1 gaat het over formatief en summatief gebruik van informatie uit toetsen. Bij programmatisch toetsen wordt het onderscheid formatief en summatief vervangen door de mate waarin er voor de student iets op het spel staat. Als je werkt volgens de principes van programmatisch toetsen, willen we je vragen de termen formatief en summatief als volgt te gebruiken. Bij formatief gaat het over het gebruik van de informatie uit datapunten voor het leerproces (low en medium stakes beslissingen). Bij summatief gaat het over het gebruik van de informatie uit datapunten om een zwaarwegende beslissing (high stakes beslissing) te nemen over de bekwaamheid van de student.    

In dimensie 5 gaat het over de inrichting van systemen. Wellicht heb je het gevoel dat je daar geen invloed op hebt. Toch denken we dat het belangrijk is om mee te nemen in de visie op toetsing, ook al heb je daar als team geen invloed op. Visie is bepalend voor technologische innovatie. Het is van belang om de wenselijke situatie op te nemen in je toetsvisie, zodat duidelijk wordt wat veranderd zou moeten worden binnen de instelling.  

:::

### Stap 5

Wanneer de laatste dimensie is behandeld, kun je de resultaten vastleggen door in de Mentimeter van de moderator te klikken op [‘View results’ en vervolgens op ‘Download PDF’](https://werkgroep-toetsen-op-afstand.github.io/visietool-toetsen/View_results.png). 