---
title: "Visietool Toetsen"
subtitle: "Klik op de pijl rechts om door te gaan."
format: 
  revealjs:
    controls: true
    background-transition: slide
    css: styles.css
    transition: slide
    title-slide-attributes: 
      data-background-color: "#9E8E67"
---

# Dimensie 1 {.smaller data-background-color="#00617E"}

> <dfn title="Toetsing waarbij het leren van de toets voorop staat. Vanuit de literatuur wordt hierbij aanbevolen om af te zien van het geven van cijfers . Door met toetsopgaven aan de slag te gaan en te leren van fouten en feedback wordt het leerproces gestimuleerd. Er wordt niet gestreefd naar een bepaald minimaal te behalen niveau. Soms ook aangeduid met Assessment for Learning of Assessment as Learning. ">Formatieve</dfn> en <dfn title="Toetsing waarbij het zo nauwkeurig mogelijk meten van een bepaald niveau van vaardigheid voorop staat. De behaalde score op een dergelijke meting wordt gebruikt voor formele toerekening van een behaald studieresultaat zoals studiepunten of een diploma. Denk bijvoorbeeld aan examens of een tentamen. Soms ook aangeduid met assessment of learning. ">summatieve</dfn> functie van toetsen in balans

In deze dimensie gaat het om de vraag hoe de verschillende doelen waarvoor een toets kan worden ingezet zich tot elkaar verhouden. Bij een <dfn title="Toetsing waarbij het leren van de toets voorop staat. Vanuit de literatuur wordt hierbij aanbevolen om af te zien van het geven van cijfers . Door met toetsopgaven aan de slag te gaan en te leren van fouten en feedback wordt het leerproces gestimuleerd. Er wordt niet gestreefd naar een bepaald minimaal te behalen niveau. Soms ook aangeduid met Assessment for Learning of Assessment as Learning. ">formatieve</dfn> inzet wordt het toetsen van studenten gebruikt om het leren te stimuleren en te besluiten over de beste vervolgstappen in het onderwijs. Bij een summatieve inzet wordt het toetsen gebruikt om vast te stellen of voldoende geleerd is en te besluiten over de kwalificatie van de student. Een formatief en een summatief gebruik van toetsen sluiten elkaar niet uit. Zo kan een toets die in eerste instantie voor summatief gebruik bedoeld is bijvoorbeeld ook op een formatieve manier worden ingezet.

## Dimensie 1 bij programmatisch toetsen

Bij programmatisch toetsen wordt het onderscheid formatief en summatief vervangen door de mate waarin er voor de student iets op het spel staat. Als je werkt volgens de principes van programmatisch toetsen, kun je de termen formatief en summatief als volgt interpreteren: Bij formatief gaat het over het gebruik van de informatie uit datapunten voor het leerproces (low en medium stakes beslissingen). Bij summatief gaat het over het gebruik van de informatie uit datapunten om een zwaarwegende beslissing (high stakes beslissing) te nemen over de bekwaamheid van de student.

## Formatief {.smallest}

1. **Toetsen met een formatieve functie geen prioriteit** 
    - In onze opleiding willen wij dat onze docenten lage prioriteit geven aan de inzet van toetsen met een formatieve functie. _Bijvoorbeeld omdat de werkdruk voor docenten al hoog genoeg ligt._
2. **Toetsen met een formatieve functie inzetten**
    - In onze opleiding willen wij dat docenten toetsen met een formatieve functie inzetten. _Bijvoorbeeld omdat studenten zo continu gestimuleerd worden om te leren._
3. **Een programma van toetsen met een formatieve functie ontwerpen**
    - In onze opleiding willen wij dat onze docenten een programma van toetsen met een formatieve functie ontwerpen. _Bijvoorbeeld omdat de formatieve toetsen dan met elkaar samenhangen en samen een goed beeld geven waar de student staat._

## Summatief {.smallest}

1. **Toetsen met een summatieve functie beperken** 
   - In onze opleiding willen wij dat onze docenten de inzet van toetsen met een summatieve functie beperken. _Bijvoorbeeld door toetsen op losse onderdelen te schrappen en samen te voegen in één <dfn title="Het moment waarop de toets wordt afgenomen of ingeleverd. ">toetsmoment</dfn>. Hierdoor is er meer ruimte in het programma voor onderwijs._   
2. **Toetsen met een summatieve functie bewust inzetten** 
    - In onze opleiding willen wij dat onze docenten de inzet van toetsen met een summatieve functie bij sommige studieonderdelen beperken of juist bewust inzetten.  _Bijvoorbeeld omdat bij bepaalde onderdelen beheersing cruciaal is voor het starten met een nieuw onderdeel dat daarop voortbouwt._  
3. **Toetsen met een summatieve functie regelmatig inplannen**
    - In onze opleiding willen wij regelmatig toetsmomenten met een summatieve functie inplannen. _Bijvoorbeeld omdat we studenten de mogelijkheid willen geven (onder)delen af te sluiten._ 
 
# Dimensie 2 {.smaller data-background-color="#00617E"}

> Toetsen en leren geïntegreerd en samenhangend, <dfn title="Indien een opleiding modulair onderwijs biedt, bestaat het onderwijsprogramma uit modules waarmee per module specifieke leerdoelen of leeruitkomsten worden behaald. Alle modules tezamen vormen de opleiding en leiden op tot een bepaald opleidingsprofiel. Indien onderwijs modulair is opgebouwd, kunnen modules afzonderlijk van elkaar gevolgd en afgerond worden.  ">modulair</dfn> waar wenselijk

In dimensie 2 gaat het ten eerste om de vraag in hoeverre men de verschillende functies (formatief en summatief) van toetsen wil integreren. Ten tweede gaat het om de vraag in hoeverre men modulair onderwijs aan wil bieden, waarin <dfn title="Een onderwijseenheid is een samenhangend onderdeel van een opleiding dat een deelnemer afsluit met een toets.">onderwijseenheden</dfn> apart toetsbaar zijn. 

## Geïntegreerd {.smallest}

1. **Duidelijk gescheiden functies**
    - In onze opleiding willen wij de functies van toetsen (formatief en summatief) duidelijk van elkaar gescheiden houden. _Bijvoorbeeld omdat wij het belangrijk vinden dat studenten eerst de kans krijgen om te leren, voordat we een (zwaarwegende) beslissing nemen over de kennis en kunde van de student._   
2. **Integratie tot op zekere hoogte**
    - In onze opleiding willen wij de functies van toetsen (formatief en summatief) duidelijk van elkaar gescheiden houden, waarbij we wel willen dat ze elkaar versterken om het leren zoveel mogelijk te stimuleren. _Bijvoorbeeld studenten oefenen met formatieve toetsen die vergelijkbaar zijn aan de <dfn title="Toetsing waarbij het zo nauwkeurig mogelijk meten van een bepaald niveau van vaardigheid voorop staat. De behaalde score op een dergelijke meting wordt gebruikt voor formele toerekening van een behaald studieresultaat zoals studiepunten of een diploma. _Denk bijvoorbeeld aan examens of een tentamen. Soms ook aangeduid met assessment of learning. ">summatieve toets</dfn>, zodat ze goed voorbereid zijn op de summatieve toets._  
3. **Volledige integratie**
    - In onze opleiding willen wij de functies van toetsen (formatief en summatief) volledig integreren. _Wij doen dit bijvoorbeeld door <dfn title="Programmatisch toetsen is een holistische manier van toetsen waarbij gekeken wordt naar de gehele ontwikkeling van de student. Het doel van programmatisch toetsen is het optimaliseren van de leerfunctie van toetsing (voor meer informatie, kijk op: programmatischtoetsen.nl; Baartman, Schilt-Mol, and Vleuten, 2020).  ">programmatisch</dfn> te toetsen. Dit houdt in dat we werken met een grote hoeveelheid informatie/feedback uit toetsen (bijvoorbeeld verslagen, reflecties en kennistoetsen), waardoor we gaandeweg een steeds beter beeld krijgen van de mate waarin de studenten voldoen aan de <dfn title="Leeruitkomsten zijn datgene wat een student moet weten, begrijpen of toepassen na een leerperiode (NVAO, 2015).">leeruitkomsten</dfn>._   

## Modulair {.smallest}

1. **Ons programma staat vast** 
    - In onze opleiding kiezen we voor een onderwijs- en <dfn title="Een toetsprogramma is meer dan de optelsom van alle toetsen van een opleiding. Een toetsprogramma is ook meer dan een willekeurige mix van toetsvormen. Van een programma is pas sprake als de combinatie van toetsvormen bewust is samengesteld, passend bij de doelen, inhoud, opbouw en structuur van het curriculum (Berkel, Bax, & Joosten-ten Brinke, 2014). ">toetsprogramma</dfn> dat vaststaat. Modules/onderwijseenheden hangen met elkaar samen en kunnen in samenhang getoetst worden. Door de <dfn title="Een doorlopende leerlijn in het curriculum is een inhoudelijke lijn waarbij studenten gedurende het onderwijsprogramma van een beginniveau naar een beoogd eindniveau worden gebracht.  ">doorlopende leerlijnen</dfn> bouwen latere toetsen voort op eerdere toetsen. Studenten kunnen zich profileren door vrije keuzeruimte, zoals een minor. _Bijvoorbeeld omdat de studieonderdelen op elkaar voortbouwen en wij daarom de volgorde bepalen._  
2. **Ons programma staat deels vast**
    - In onze opleiding willen wij dat een deel van de modules/onderwijseenheden vaststaat. Het onderwijs en de toetsing in deze modules hangen met elkaar samen. Daarnaast is er een substantieel deel van de opleiding waarin studenten zelf (de volgorde van) modules mogen kiezen. Deze modules worden los van elkaar getoetst. _Bijvoorbeeld omdat we naast de voor het toekomstige beroep essentiële modules waar mogelijk onze studenten keuzes willen geven._  
3. **Ons programma is volledig flexibel in te richten**
    - In onze opleiding willen wij studenten in staat stellen om hun persoonlijke leerpad of programma samen te stellen. De modules/onderwijseenheden staan allemaal los van elkaar en worden ook los van elkaar getoetst. _Bijvoorbeeld omdat we hierdoor studenten de kans geven om in hun eigen tempo te studeren en zelf de regie te hebben over hun eigen onderwijsprogramma._  

# Dimensie 3 {.smaller data-background-color="#00617E"}

> Toetsen <dfn title="Een authentieke toets is een toets die zo veel mogelijk overeenkomt met de beroepspraktijk waartoe opgeleid wordt. Vijf dimensies beïnvloeden de mate van authenticiteit: de taak, de fysieke context, de sociale context, de vorm (assessmentmethode) en de beoordelingscriteria (Gulikkers, 2008) ">authentiek</dfn> en gevarieerd

In deze dimensie gaat het ten eerste om de vraag in welke mate men de toetsen wil laten aansluiten op de praktische toepassing in werk en maatschappij. Dat kan door te kijken naar de vijf dimensies die de authenticiteit van een toets beïnvloeden: de taak, de fysieke context, de sociale context, de vorm (assessmentmethode) en de beoordelingscriteria (Gulikkers, 2008). De tweede vraag die centraal staat is in welke mate men ruimte wil bieden voor een gevarieerd aanbod aan toetsen. 

## Authentiek {.smallest}

1. **Geen prioriteit aan authentiek toetsen**
    - In onze opleiding geven wij geen prioriteit aan authentiek toetsen. _Bijvoorbeeld omdat de opleiding vooral gericht is op het ontwikkelen van een brede kennisbasis._  
2. **In toenemende mate authentiek toetsen**
    - In onze opleiding willen wij meer authentiek toetsen naarmate de student verder komt in zijn of haar opleiding. _Bijvoorbeeld omdat het begin van de opleiding meer op kennis is gericht en naarmate de opleiding vordert, de nadruk meer op competenties komt te liggen._ 
3. **Zo veel mogelijk authentiek toetsen**
    - In onze opleiding willen we door de gehele opleiding heen authentiek toetsen zoveel mogelijk inzetten (daar waar relevant en mogelijk). _Bijvoorbeeld omdat studenten dan al vroeg in de opleiding vertrouwd raken met de (toekomstige) beroepscontext en de relevantie zien van wat ze in de opleiding moeten leren._  

## Gevarieerd {.smallest}

1. **Gestandaardiseerde toetsvormen**
    - In onze opleiding hebben docenten keuze uit een beperkt, vast aanbod aan <dfn title="en gestandaardiseerde toetsvorm is een toetsvorm die qua inhoud en omstandigheden voor iedereen gelijk is. ">gestandaardiseerde toetsvormen</dfn>. Er wordt voorgeschreven welke toetsvorm je als docent in mag zetten. _Bijvoorbeeld als docent mag je uitsluitend kiezen om te toetsen middels een kennistoets, omdat we hierdoor duidelijkheid creëren en procedures voor de borging van de kwaliteit van de toetsen eenvoudiger zijn._
2. **Toetsvorm keuze van de docent**
    - In onze opleiding willen wij docenten alle ruimte bieden om zelf een keuze te maken voor een toetsvorm die past bij de leerdoelen. Docenten hebben voldoende <dfn title="Met toetsbekwaamheid wordt in het toetsweb verwezen naar de deskundigheid die bij actoren binnen de opleiding aanwezig moet zijn om kwaliteit te realiseren op alle toetsentiteiten (Van Berkel, Sluijsmans & Joosten-ten Brinke, 2015). Specifiek voor de entiteit toetsen geldt dat de toetsbekwaamheid van docenten, examencommissies en andere betrokkenen van essentieel belang is: elke docent moet in staat zijn om toetsinformatie te interpreteren en te gebruiken om vast te stellen waar studenten staan en hoe deze informatie verder kan bijdragen aan het leren van de student (Straetmans, 2006). Voor meer informatie, zie ook www.toetsweb.nl. ">toetsbekwaamheid</dfn> om de juiste toetsvorm te kiezen of worden hierbij ondersteund door experts en adviseurs. _Bijvoorbeeld omdat docenten hierdoor professionele ruimte ervaren doordat wij vertrouwen op hun expertise en professionaliteit._
3. **Gevarieerd toetsprogramma**
    - In onze opleiding willen wij dat docententeams een bewust samengesteld gevarieerd <dfn title="Een toetsprogramma is meer dan de optelsom van alle toetsen van een opleiding. Een toetsprogramma is ook meer dan een willekeurige mix van toetsvormen. Van een programma is pas sprake als de combinatie van toetsvormen bewust is samengesteld, passend bij de doelen, inhoud, opbouw en structuur van het curriculum (Berkel, Bax, & Joosten-ten Brinke, 2014). ">toetsprogramma</dfn> maken. Binnen het team is hiervoor voldoende toetsbekwaamheid of het team wordt hierbij ondersteund door experts en adviseurs. _Bijvoorbeeld omdat door deze manier van werken we goed zicht hebben op het totale programma, waardoor de studeerbaarheid wordt vergroot._ 

# Dimensie 4 {.smaller data-background-color="#00617E"}

> Plaats- & <dfn title="Studenten kunnen zelf de tijd kiezen waarop ze de toets maken.">tijdonafhankelijk</dfn> toetsen

In deze dimensie gaat het om de vraag in hoeverre men <dfn title="Flexibel onderwijs is onderwijs dat studenten keuzevrijheid biedt. Flexibel onderwijs kan te maken hebben met wat studenten leren (inhoudelijke keuzevrijheid, onderwijs passend bij hun achtergrond) en hoe studenten leren (op hun eigen tijd en plaats en in hun eigen tempo, op hun eigen niveau en manier).">flexibel<dfn> wil zijn in de plaatsen en tijdstippen waarop toetsen kunnen worden afgenomen.

## Plaatsonafhankelijk {.smallest}

1. **Plaatsafhankelijk**
    - In onze opleiding willen wij dat alle studenten op dezelfde plaats toetsen maken. _Bijvoorbeeld omdat we de afnamecondities voor de studenten zoveel mogelijk gelijk willen houden._ 
2. **Keuze hangt af van de toetsvorm**
    - In onze opleiding willen wij dat de ontwerper van de toets bekijkt of er bij de gekozen toetsvorm mogelijkheden zijn om de student de afnameplek te laten kiezen. Plaatsonafhankelijkheid is geen doel op zich. _Bijvoorbeeld studenten kunnen waar passend bij bepaalde <dfn title="Leeruitkomsten zijn datgene wat een student moet weten, begrijpen of toepassen na een leerperiode (NVAO, 2015).">leeruitkomsten</dfn> zelf kiezen waar ze een beroepsproduct maken._
3. **Plaatsonafhankelijk **
    - In onze opleiding willen wij dat <dfn title="Studenten kunnen zelf de locatie kiezen waar ze de toets maken.">plaatsonafhankelijkheid</dfn> van de toets gezien wordt als <dfn title="De ontwerpcriteria zijn de criteria waaraan een toets moet voldoen.">ontwerpcriterium</dfn>. Wij willen de student zoveel mogelijk de ruimte geven om zelf te kiezen waar die de toets aflegt. _Bijvoorbeeld omdat we hiermee zorgen voor veel flexibiliteit voor studenten, dit vergroot de studeerbaarheid en de <dfn title="Als studenten zelf de regie nemen, staan docenten minder aan het roer. Studenten nemen zelf de verantwoording om tot leren te komen.  ">regie van studenten</dfn>._ 

## Tijdonafhankelijk {.smallest}

1. **Tijdafhankelijk**
    - In onze opleiding willen wij dat het moment waarop de toets wordt afgenomen voor iedereen gelijk is. _Bijvoorbeeld omdat het dan voor docenten en studenten duidelijk is wanneer de <dfn title="Het moment waarop de toets wordt afgenomen of ingeleverd. ">toetsmomenten</dfn> en herkansingen zijn._  
2. **Keuze uit meerdere toetsmomenten **
    - In onze opleiding willen wij studenten ruimte geven om zelf te kiezen wanneer zij de toets afleggen, door studenten meerdere toetsmomenten aan te bieden gedurende het jaar. _Bijvoorbeeld om studenten ruimte te bieden om te versnellen of te vertragen en het ook werkbaar te houden voor docenten._  
3. **Tijdonafhankelijk**
    - In onze opleiding willen wij studenten zoveel mogelijk de ruimte geven om zelf te kiezen wanneer zij de toets afleggen. _Hiermee zorgen we voor veel flexibiliteit voor studenten._ 

# Dimensie 5 {.smaller data-background-color="#00617E"}

> <dfn title="Het afnemen van toetsen impliceert meer dan het construeren van toetsvragen; het is een proces dat verschillende fasen en stappen kent (Berkel, Bax, & Joosten-ten Brinke, 2014).">Toetsproces</dfn> in samenhang en in samenwerking gedigitaliseerd en georganiseerd

In deze dimensie gaat het om de vraag in hoeverre digitale (toets)systemen samenhangen. Met samenhang wordt bedoeld dat de systemen met elkaar geïntegreerd zijn, zodat gegevens uitwisselbaar zijn. Bijvoorbeeld cijfers komen automatisch in registratiesystemen te staan. Een ander voorbeeld is dat de registratie van toetstijdverlengingen door de studentendecaan automatisch wordt gekoppeld aan de verlengde extra tijd in de <dfn title="De toetsapplicatie is de applicatie waarin de toets gemaakt wordt.">toetsapplicatie</dfn>. De tweede vraag die centraal staat is in hoeverre men bij het doorlopen van de <dfn title="De toetscyclus omvat het (cyclische) proces van ontwerpen, afnemen, nakijken, analyseren en evalueren van toetsen.">toetscyclus</dfn> samenwerking verwacht.

## Toelichting

In deze dimensie gaat het over de inrichting van systemen. Wellicht heb je het gevoel dat je daar geen invloed op hebt. Toch is het belangrijk om mee te nemen in de visie op toetsing, ook als je daar als team geen invloed op hebt. Visie is bepalend voor technologische innovatie. Het is daarom van belang om de wenselijke situatie op te nemen in je toetsvisie, zodat duidelijk wordt wat veranderd zou moeten worden binnen de instelling.

## Samenhang {.smallest}

1. **Geen prioriteit samenhang**
    - In onze opleiding geven wij de samenhang van digitale systemen geen prioriteit. _Bijvoorbeeld omdat er al veel tijd gaat naar de toetsing. We besteden daarom geen tijd aan het optimaal integreren van de systemen._ 
2. **Zo veel mogelijk samenhang**
    - In onze opleiding willen wij ons toetsproces zo inrichten dat digitale systemen zo veel als mogelijk met elkaar samenhangen. _Bijvoorbeeld omdat dan bepaalde processen uit de toetscyclus in ons toetsproces geautomatiseerd kunnen worden._ 
3. **Altijd samenhang**
    - In onze opleiding willen wij ons toetsproces zo inrichten dat digitale systemen altijd met elkaar samenhangen. Docenten maken alleen gebruik van systemen die met elkaar geïntegreerd zijn. _Bijvoorbeeld omdat het voor ons onderwijsconcept van belang is dat docenten dezelfde digitale systemen gebruiken. Deze systemen ondersteunen het onderwijs- en toetsproces._ 

## Samenwerking  {.smallest}

1. **Docenten werken samen**
    - In onze opleiding willen wij dat docenten samenwerken bij het doorlopen van de toetscyclus. _Bijvoorbeeld docenten werken samen aan een toetsmatrijs of kijken bij elkaar mee bij de evaluatie van een toets._ 
2. **In gezamenlijkheid binnen de opleiding**
    - In onze opleiding willen wij dat het doorlopen van de toetscyclus een gezamenlijke aangelegenheid is van het gehele docententeam. _Bijvoorbeeld omdat we het samenstellen van een gevarieerd <dfn title="Een toetsprogramma is meer dan de optelsom van alle toetsen van een opleiding. Een toetsprogramma is ook meer dan een willekeurige mix van toetsvormen. Van een programma is pas sprake als de combinatie van toetsvormen bewust is samengesteld, passend bij de doelen, inhoud, opbouw en structuur van het curriculum (Berkel, Bax, & Joosten-ten Brinke, 2014). ">toetsprogramma</dfn> als gedeelde verantwoordelijkheid zien._  
3. **In gezamenlijkheid óók met partners**
    - In onze opleiding willen wij dat het doorlopen van de toetscyclus een gezamenlijke aangelegenheid is van het gehele docententeam en partners (Bijvoorbeeld werkveld, andere opleidingen, lectoraten/practoraten en examenleveranciers). _Bijvoorbeeld docenten en betrokkenen uit het vakgebied werken samen aan een gezamenlijke <dfn title="Een itembank is een digitale verzameling vragen die voor een toets gebruikt kunnen worden. De toetsvragen kunnen worden voorzien van kenmerken, zoals metadata, tags, trefwoorden en labels. Ook de resultaten van de toetsen en van de (psychometrische) analyses worden bewaard in de itembank. ">itembank</dfn>. _

# {data-background-color="#9E8E67"}