## Voorbereiding voor de moderator

Bereid als moderator de sessie als volgt voor:

1. Zorg voor een multidisciplinair team van 5 tot 7 personen waarmee je na wilt denken over de (digitale) toetsvisie. Je kunt zelf ook deelnemen aan de discussie.  
2. Reserveer een ruimte met een beeldscherm/projectorscherm. Ga voor de sessie uit van een tijdsduur van 1,5 à 2 uur. 
3. Nodig de relevante betrokkenen uit voor een sessie met de Visietool en vraag hen om voorafgaand aan de sessie [het rapport Toekomstperspectief op (digitaal) toetsen en beoordelen](https://www.versnellingsplan.nl/Kennisbank/toekomstperspectief-op-digitaal-toetsen-en-beoordelen/) te lezen en hun telefoon of laptop naar de sessie mee te nemen.   
4. Vraag één van de deelnemers om te notuleren tijdens de bijeenkomst. Het is handig als deze notulist ook de tijd heeft om na afloop een eerste versie van een visie te kunnen schrijven op basis van de opgehaalde input. De notulist kan ook deelnemen aan de sessie. 
5. Aan het begin van de sessie geef je een korte introductie. Hiervoor kun je de [PowerPoint](200924Introductievideo.pptx) of de [introductievideo](https://youtu.be/irJLWzgdX7g) gebruiken. 
6. Tijdens de sessie worden bij iedere dimensie vaste stappen doorlopen. Hierbij gebruik je de vetgedrukte producten, je vindt deze onder deze instructie.  
    1. Alle deelnemers lezen de omschrijving van de dimensie en de stellingen bij de twee bijbehorende componenten. Deze informatie kun je tijdens de bijeenkomst op twee manieren delen met de deelnemers: 
        * door de [digitale versie van de stellingen](visietool_toetsen.qmd) te laten zien tijdens de bijeenkomst op een groot scherm of deelnemers deze open te laten zetten op een laptop. Als je als moderator je muis over bepaalde belangrijke begrippen beweegt, dan zie je de definitie van dat begrip verschijnen.  
        * door voor iedere deelnemer de [Handoout stellingen visietool](Definitief_Handout_Vijf_dimensie_visietool_incl_begrippenlijst.pdf) te printen. Achteraan in de handout zit een begrippenlijst.  
    2. Na het lezen van de omschrijving bepalen alle deelnemers eerst individueel de eigen positie op de twee componenten en voeren deze in in de beschikbare [Mentimeter](https://www.mentimeter.com/app/presentation/n/albx6yapo5dwg64cjiwedcrpbcynvcc2/invite?utm_campaign=Invited%20to%20collaborate%20on%20presentation&utm_content=Email%231%3A%20Invite%20to%20collaborate%20-%20name%20%2B%20last%20name%20exists&utm_medium=email&utm_source=transactional). Open van tevoren de Mentimeter in je eigen Mentimeteraccount, die van je organisatie, of maak hiervoor een (gratis) account aan. Mogelijk verschijnt er de melding ‘This presentation uses features that are not included in your plan’, deze melding kun je negeren. 
    3. Deelnemers schrijven eventueel hun motivatie voor de scores op (in de handout). 
    4. Vervolgens volgt er een plenaire discussie, waarbij de notulist zoveel mogelijk input vastlegt voor de visie op (digitaal) toetsen.  