---
titel: "Werkwijze"
format:
  html:
    toc: true
    toc-location: left
    smooth-scroll: true
---

::: {.lead}

De Visietool (digitaal) toetsen is het beste in te zetten als gesprekstool in een sessie: 

* van ongeveer **1,5 à 2 uur**;  
* met **5-7 personen**; 
* met een **multidisciplinair team**, denk aan: onderwijsadviseur, toetsdeskundige, opleidingsdirecteur, examencommissie, opleidingscommissie, docent, ICTO Coach, etc.;  
* onder begeleiding van een **moderator**; 
* met een **notulist**. 

De Visietool bestaat uit de volgende producten die ingezet kunnen worden bij een sessie:

Stellingen:
In de sessie heeft iedere deelnemer de stellingen voor zich. Dit kan digitaal of met de papieren handout.

* Stellingen visietool digitaal
* Handout stellingen visietool

Introductie van de sessie:
De sessie start met een introductie. De moderator kan deze introductie zelf geven met de daarvoor beschikbare powerpoint, of kan de introductievideo laten zien.
* PowerPoint introductie sessie visietool
* Introductievideo sessie visietool

Mentimeter
Tijdens de sessie wordt een mentimeter gebruikt. Voeg de mentimeter toe aan je eigen account, door het mentimeter template hier te openen en vervolgens rechtsonderin te kiezen voor "Copy to your account". 
* Mentimenter template


:::

::: {.grid}

::: {.g-col-12 .g-col-md-6}

::: {.card .text-white .bg-primary .rounded-3 .mx-auto}

::: {.card-body}

## Stellingen & Mentimeter {.card-title}

::: {.card-text}

* [Presentatie stellingen visietool](visietool_toetsen.qmd){.link-light}
* [Open hier de mentimeter template](https://www.mentimeter.com/app/presentation/al85wxmwcturymgcdsjsenu7cs9wfnar/fjdn9teuz6cz){.link-light}


:::

:::

:::

:::

::: {.g-col-12 .g-col-md-6}

::: {.card .text-white .bg-primary .rounded-3 .mx-auto}

::: {.card-body}

## Documenten {.card-title}

::: {.card-text}

* [Handout stellingen visietool](Definitief_Handout_Vijf_dimensie_visietool_incl_begrippenlijst.pdf){.link-light}
* [Toekomstperspectief op (digitaal) toetsen en beoordelen](https://www.versnellingsplan.nl/Kennisbank/toekomstperspectief-op-digitaal-toetsen-en-beoordelen/){.link-light}

:::

:::

:::

:::

:::


## Voorbereiding voor de moderator

Bereid als moderator de sessie als volgt voor:

1. Zorg voor een multidisciplinair team van 5 tot 7 personen waarmee je na wilt denken over de (digitale) toetsvisie. Je kunt zelf ook deelnemen aan de discussie.  
2. Reserveer een ruimte met een beeldscherm/projectorscherm. Ga voor de sessie uit van een tijdsduur van 1,5 à 2 uur. 
3. Nodig de relevante betrokkenen uit voor een sessie met de Visietool en vraag hen om voorafgaand aan de sessie [het rapport Toekomstperspectief op (digitaal) toetsen en beoordelen](https://www.versnellingsplan.nl/Kennisbank/toekomstperspectief-op-digitaal-toetsen-en-beoordelen/) te lezen en hun telefoon of laptop naar de sessie mee te nemen.   
4. Vraag één van de deelnemers om te notuleren tijdens de bijeenkomst. Het is handig als deze notulist ook de tijd heeft om na afloop een eerste versie van een visie te kunnen schrijven op basis van de opgehaalde input. De notulist kan ook deelnemen aan de sessie. 
5. Aan het begin van de sessie geef je een korte introductie. Hiervoor kun je de PowerPoint of de [introductievideo](https://youtu.be/irJLWzgdX7g) gebruiken. 
6. Tijdens de sessie worden bij iedere dimensie vaste stappen doorlopen. Hierbij gebruik je de vetgedrukte producten, je vindt deze onder deze instructie.  
    1. Alle deelnemers lezen de omschrijving van de dimensie en de stellingen bij de twee bijbehorende componenten. Deze informatie kun je tijdens de bijeenkomst op twee manieren delen met de deelnemers: 
        * door de [digitale versie van de stellingen](visietool_toetsen.qmd) te laten zien tijdens de bijeenkomst op een groot scherm of deelnemers deze open te laten zetten op een laptop. Als je als moderator je muis over bepaalde belangrijke begrippen beweegt, dan zie je de definitie van dat begrip verschijnen.  
        * door voor iedere deelnemer de [Handoout stellingen visietool](Definitief_Handout_Vijf_dimensie_visietool_incl_begrippenlijst.pdf) te printen. Achteraan in de handout zit een begrippenlijst.  
    2. Na het lezen van de omschrijving bepalen alle deelnemers eerst individueel de eigen positie op de twee componenten en voeren deze in in de beschikbare Mentimeter. Open van tevoren de Mentimeter in je eigen Mentimeteraccount, die van je organisatie, of maak hiervoor een (gratis) account aan. Mogelijk verschijnt er de melding ‘This presentation uses features that are not included in your plan’, deze melding kun je negeren. 
    3. Deelnemers schrijven eventueel hun motivatie voor de scores op (in de handout). 
    4. Vervolgens volgt er een plenaire discussie, waarbij de notulist zoveel mogelijk input vastlegt voor de visie op (digitaal) toetsen.  




 
## Benodigdheden voor tijdens de sessie

* [Toekomstperspectief op (digitaal) toetsen en beoordelen](https://www.versnellingsplan.nl/Kennisbank/toekomstperspectief-op-digitaal-toetsen-en-beoordelen/) 
Vraag de deelnemers de toekomstperspectieven ter voorbereiding door te lezen 
* [Mentimeter](https://www.mentimeter.com/app/presentation/al85wxmwcturymgcdsjsenu7cs9wfnar/fjdn9teuz6cz)
Voeg de mentimeter toe aan je eigen account. Knop rechts onderin: “Copy to your account”. 
* [Webpagina met dimensies, componenten en stellingen](visietool_toetsen.qmd) 
Open deze pagina tijdens de sessie en laat deelnemers de informatie lezen voordat zij een keuze maken in de mentimeter 
* [Handout met dimensies, componenten, stellingen en ruimte voor onderbouwing](Definitief_Handout_Vijf_dimensie_visietool_incl_begrippenlijst.pdf) 
Je kunt ervoor kiezen om deze hand-out voor iedere deelnemer te printen, zodat zij de informatie op papier kunnen lezen en hun onderbouwing kunnen opschrijven.  

## Tijdens de sessie 

Begeleid de deelnemers stap voor stap door onderstaande procedure.  

### Stap 1

Geef aan de start van de sessie een korte toelichting op het doel en de werkwijze van de Visietool. Je kunt hier de PowerPoint of de Instructievideo voor gebruiken. Licht hier toe dat jij de moderator bent en wie notuleert. 

### Stap 2

Start de Mentimeter op, klik op ‘Present’, en laat de betrokkenen met hun laptop of telefoon deelnemen aan de Mentimeter door de code die bovenin de dia’s van de presentatie staat in te vullen in [www.menti.com](www.menti.com).  

:::{.repeat}

### Stap 3

Vraag deelnemers de eerste dimensie en de bijbehorende twee componenten met stellingen te lezen op het scherm, of vanaf de uitgeprinte hand-out. Laat de deelnemers per component een keuze maken in de mentimeter voor één van de stellingen (keuze voor 1, 2 of 3): welke stelling past volgens hen het beste bij hoe zij de opleiding (in de toekomst) voor zich zien? Licht toe dat de schuingedrukte zinnen bij de stellingen mogelijke verantwoordingen zijn, en deze niet van toepassing hoeven te zijn. De deelnemers kunnen voor zichzelf hun keuze en hun motivatie daarvoor op de hand-out invullen. Vervolgens vullen de betrokkenen in de Mentimeter in welke stellingen (1, 2 of 3) zij hebben gekozen bij de twee componenten van deze dimensie. Geef voor deze stap maximaal 5 minuten de tijd. 

### Stap 4

Laat de groep nu de resultaten in de Mentimeter zien. Laat deelnemers hun keuzes onderbouwen en laat hen met elkaar in gesprek gaan over de overeenkomsten en verschillen in opvattingen, met als doel om tot een gezamenlijk besluit te komen. Neem hier ongeveer 10 minuten de tijd voor. Laat de notulist goed notuleren; het gaat niet om de uiteindelijke score, maar de onderbouwing ervan.  

**Let op**: in de grafiek zie je niet altijd hoe vaak gescoord is op een item. Wanneer je de muis over de grafiek beweegt, kun je dit wel zien. 

**Herhaal stap 3 en 4 voor elke dimensie.**

Inhoudelijke toelichting:  
Bij dimensie 1 gaat het over formatief en summatief gebruik van informatie uit toetsen. Bij programmatisch toetsen wordt het onderscheid formatief en summatief vervangen door de mate waarin er voor de student iets op het spel staat. Als je werkt volgens de principes van programmatisch toetsen, willen we je vragen de termen formatief en summatief als volgt te gebruiken. Bij formatief gaat het over het gebruik van de informatie uit datapunten voor het leerproces (low en medium stakes beslissingen). Bij summatief gaat het over het gebruik van de informatie uit datapunten om een zwaarwegende beslissing (high stakes beslissing) te nemen over de bekwaamheid van de student.    

In dimensie 5 gaat het over de inrichting van systemen. Wellicht heb je het gevoel dat je daar geen invloed op hebt. Toch denken we dat het belangrijk is om mee te nemen in de visie op toetsing, ook al heb je daar als team geen invloed op. Visie is bepalend voor technologische innovatie. Het is van belang om de wenselijke situatie op te nemen in je toetsvisie, zodat duidelijk wordt wat veranderd zou moeten worden binnen de instelling.  

:::

### Stap 5

Wanneer de laatste dimensie is behandeld, kun je de resultaten vastleggen door in de Mentimeter van de moderator te klikken op [‘View results’ en vervolgens op ‘Download PDF’](https://werkgroep-toetsen-op-afstand.github.io/visietool-toetsen/View_results.png). 

## Het vervolg

Het invullen van de Visietool vormt niet het eindpunt maar het startpunt van het bepalen van de visie van de opleiding. De gezamenlijk gekozen stellingen met bijbehorende verantwoording vormen input voor het (her)schrijven van de officiële visie van de opleiding. Laat de betrokkenen afspraken met elkaar maken over het (her)schrijven van deze officiële visie. 
 


<!-- [Start](visietool_toetsen.qmd){.btn .btn-primary target="_blank"} -->

```{r, echo=FALSE, eval=FALSE}
rmarkdown::render("visietool_toetsen.qmd", output_format = "pdf_document")
```

