---
title: ""
format:
  typst:
    template: template.typ
    template-partials: []
    typst-template-args:
      dimension-number: "2"
      dimension-title: "AI-bewust onderwijs en toetsen"
      component-title: "Component 2: AI-gebruik bij toetsen met een summatieve functie/examineren"
---

```{=typst}
#option("1", "AI-gebruik niet toestaan")[
```

In onze opleidingen mogen studenten bij toetsen met een summatieve
functie/examinering in een gecontroleerde omgeving geen gebruik maken van AI.

*Bijvoorbeeld omdat op deze manier de individuele beheersing van de leerdoelen
zonder hulpmiddelen betrouwbaar vastgesteld kan worden.*

```{=typst}
]
```

```{=typst}
#option("2", "AI-gebruik toestaan onder toezicht en verantwoording")[
```

In onze opleiding mogen studenten bij specifieke toetsen met een summatieve
functie/examinering AI gebruiken, mits ze het gebruik van AI volledig
transparant maken.

*Bijvoorbeeld omdat dit studenten leert AI bewust en doordacht in te zetten,
zoals zij dit straks ook in hun beroepspraktijk zullen moeten doen.*

```{=typst}
]
```

```{=typst}
#option("3", "AI-gebruik verplichten")[
```

In onze opleiding verplichten we studenten AI actief in te zetten bij toetsen
met een summatieve functie/examinering, wanneer de leerdoelen daarom vragen.

*Bijvoorbeeld omdat we zo zowel het eindresultaat als hun verantwoord gebruik
van AI kunnen beoordelen.*

```{=typst}
]
```
